name: JazyToys Package
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Build Android App
        run: |
          sudo apt-get update
          sudo apt-get install -y libffi-dev libssl-dev autoconf pkg-config
          pip install buildozer cython
          yes | buildozer init
          sed -i 's/requirements = python3,kivy/requirements = python3,kivy/g' buildozer.spec
          sed -i 's/#orientation = landscape/orientation = portrait/g' buildozer.spec
          yes | buildozer -v android debug
      - name: Save APK
        uses: actions/upload-artifact@v4
        with:
          name: JazyToys-App
          path: bin/
